### PR TITLE
Update clipboardToTxt.py

### PR DESCRIPTION
**Pull request by bolapara**
Make more Pythonic.  Handle errors.

### CODE REVIEW

**Comment by bolapara** [comment]
These should really be collapsed.  Last time I edit in the GitHub editor without testing.

**Review by Crevette3 — COMMENTED** [review]
I looked at the code and tried it out. I like the exception handling, before it would crash if you copied any special character. It looks like whatever I copy keeps some of its original format, ie, if a string of copied text has a newline that is how it is saved in the text document, I think this is a great addition.

**Review by Crevette3 — DISMISSED** [review]
One thing that I would want to be added,(which I don't know how to add off the top of my head) is when the clipboard is saved to the text document, it skips and places a marker before saving the next copied text. So the text document would look something like this:

Copied text
$
more copied text
$
even more copied text

**Comment by ekivolowitz** [comment]
Sure. I'll edit the code to do that @Crevette3

**Comment by Crevette3** [comment]
Cool, thanks @ekivolowitz

**Comment by bolapara** [comment]
Added marker between pastes

**Comment by bolapara** [comment]
@Crevette3 , not sure how to mark your requested changes as resolved but the last diff does what you want.

**Comment by Crevette3** [comment]
@bolapara Your solution to add a $ marker in each newline would prevent text from being saved in the original format it was copied in, @ekivolowitz his solution added a $ sign and was able to keep the text in the format it was copied. Using this line:

`f.write('{}\n$\n'.format(paste))`

**Comment by Crevette3** [comment]
@bolapara Thanks for the help.

**Comment by bolapara** [comment]
`f.write('{}\n{}\n'.format(paste, MARKER))` does literally the same thing, but with a customizable marker.  The format() method takes arguments and replaces the '{}' with that argument.  So '{}\n{}\n'.format('a', 'b') gives you the string:  'a\nb\n'.

**Comment by Crevette3** [comment]
Weird, for some reason the first time I tried your code, any amount of text would be saved on one line in the text document. Now when I try it, the text keeps its original formatting.

**Comment by ekivolowitz** [comment]
@bolapara I agree. Your solution is more extensible and pythonic.

**Pull request closed without merging**
